spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todos?serverTimezone=UTC
    username: test
    password: 1234
#   driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:mybatis/config/config.xml
